version: "3"
services:
  client:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - chat-app

  server:
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge